name: security scan

on: [pull_request]

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform security scan
        uses: reviewdog/action-tfsec@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: "sandbox/terraform"
          reporter: github-pr-review
          fail_on_error: "true"
          filter_mode: "nofilter"
          level: "warning"